### ISSUE TITLE
Configurable Definitions

### ISSUE THREAD

**Issue by jirhiker** [NMWDI/PySTA#1]
add the ability to specify a definitions.yaml file 

then you could do things like

```
stac.add_datastream(definiition='gwl', ... )
```
and in definitiions.yaml

```
datastreams:
  gwl:
     name: Groundwater Levels
     description:  blah blah blah
```
